version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: andprof/ac2_ca:latest
    environment:
      DB_HOST: database
    ports:
      - "8585:8080"

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "9090:8080"   # Porta padrão do Jenkins
      - "50000:50000" # Para agentes Jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Permite que o Jenkins gerencie containers no host
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin123 # Substitua por algo mais seguro

volumes:
  db-volume:
  jenkins-data:
